endpoints:
  npis:
    oAuth:
      url: "http://testNpisOauth"
      username: "test"
      password: "test"
    url638_1: "http://1st"
    url638_2: "http://2nd"
    npisUrl: "http://npis"

  ipne:
    oAuth:
      url: "http://testipneOauth"
      username: "test"
      password: "test"
    ipneUrl: "http://ipne"
    ipneUserName: "abc"
    ipnePassword: "test"
