package com.example.demo.kafkaCaching;

package au.com.optus.renaissanceCamunda.worker;

import java.util.HashMap;
import java.util.Map;
import java.util.Properties;

import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.common.serialization.StringSerializer;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import io.camunda.zeebe.client.api.response.ActivatedJob;
import io.camunda.zeebe.client.api.worker.JobClient;
import io.camunda.zeebe.spring.client.annotation.JobWorker;

import au.com.optus.renaissanceCamunda.service.KafkaConfigurationService;
import au.com.optus.renaissanceCamunda.service.AwsSecretsService;
import au.com.optus.renaissanceCamunda.service.KafkaOAuthTokenService;
import au.com.optus.renaissanceCamunda.model.KafkaConfig;

@Component
public class KafkaSendWorker {

    @Autowired
    private KafkaConfigurationService kafkaConfigService;

    @Autowired
    private AwsSecretsService awsSecretsService;

    @Autowired
    private KafkaOAuthTokenService tokenService;  // Your Caffeine 5-min token cache

    @JobWorker(type = "send-to-kafka-topic")
    public void sendMessageToKafka(final JobClient client, final ActivatedJob job) {

        try {
            // ----------------------------------------
            // 1) Extract message from workflow
            // ----------------------------------------
            Map<String, Object> vars = job.getVariablesAsMap();
            String message = vars.get("message").toString();

            // ----------------------------------------
            // 2) Load config from ConfigMap (bootstrap, topic, additionalProps)
            // ----------------------------------------
            KafkaConfig cfg = kafkaConfigService.getKafkaConfiguration();
            String topic = cfg.getTopic();

            // ----------------------------------------
            // 3) Build Kafka properties manually
            // ----------------------------------------
            Properties props = new Properties();

            // Kafka basics
            props.put("bootstrap.servers", cfg.getBootstrapServer());
            props.put("key.serializer", StringSerializer.class.getName());
            props.put("value.serializer", StringSerializer.class.getName());

            // ----------------------------------------
            // 4) Add all additional security properties from configmap
            // ----------------------------------------
            Map<String, String> additionalProps = cfg.getAdditionalProperties();
            props.putAll(additionalProps);

            // ----------------------------------------
            // 5) Fetch AWS secrets → replace dynamicUser & dynamicPassword
            // ----------------------------------------
            Map<String, String> awsSecrets = awsSecretsService.getSecret();
            String clientId = awsSecrets.get("sdsyncKafkaClientId");
            String clientSecret = awsSecrets.get("sdsyncKafkaClientSecret");

            // ----------------------------------------
            // 6) Build JAAS config (dynamic user, secret + token)
            // ----------------------------------------
            String jaas = additionalProps.get("sasl.jaas.config");

            // Replace placeholders from configMap
            jaas = jaas.replace("dynamicUser", clientId)
                    .replace("dynamicPassword", clientSecret);

            // ----------------------------------------
            // 7) Fetch cached OAuth token (generated by your TokenService)
            // ----------------------------------------
            String token = tokenService.getToken();

            // Inject token into JAAS (manual OAuth mode)
            jaas = jaas + " oauthToken=\"" + token + "\";";

            props.put("sasl.jaas.config", jaas);

            // ----------------------------------------
            // 8) Create Kafka Producer manually
            // ----------------------------------------
            KafkaProducer<String, String> producer = new KafkaProducer<>(props);

            // ----------------------------------------
            // 9) Send message to Kafka topic
            // ----------------------------------------
            producer.send(new ProducerRecord<>(topic, message));

            producer.flush();
            producer.close();

            // ----------------------------------------
            // 10) Complete Camunda job
            // ----------------------------------------
            client.newCompleteCommand(job.getKey()).send().join();

        } catch (Exception e) {
            client.newFailCommand(job.getKey())
                    .retries(0)
                    .errorMessage(e.getMessage())
                    .send()
                    .join();
        }
    }
}

